adjustments

diff --git a/infra/admin-service-account b/infra/admin-service-account
--- a/infra/admin-service-account
+++ b/infra/admin-service-account
@@ -1,25 +1,34 @@
 #!/usr/bin/env bash
 
+set -e
+
+self=${0##*/}
+ALIAS=$(readlink "${0%$self}".alias)
+
 # CUSTOMIZE as needed ::>>
-ALIAS=kas
-KEYFILE=$HOME/projects/$ALIAS/.json
+KEYFILE=$HOME/.$ALIAS-auth.json
 PROJECT=sentience-reinforce
 REGION=europe-west4
 ZONE=$REGION-a
 SA_NAME=admin-123
 # <<:: CUSTOMIZE as needed
 
-email=$SA_NAME@$PROJECT.iam.gserviceaccount.com
+SA_SUFFIX=gserviceaccount.com
+EMAIL=$SA_NAME@$PROJECT.iam.$SA_SUFFIX
 
 
 ensure_logged_in() {
-    [ "$(gcloud auth list --format 'value(account)' --filter status=active)" = $USER@kth.se ] ||
-        gcloud auth login
+    # make sure the active account is NOT a GCP service account
+    [ "$(gcloud auth list \
+        --format 'value(account)' \
+        --filter 'status=active -account~$SA_SUFFIX')" ] || gcloud auth login
 }
 
 ensure_logged_out() {
-    ! [ "$(gcloud auth list --format 'value(account)' --filter account=$USER@kth.se)" ] ||
-        gcloud auth revoke $USER@kth.se
+    # make sure only GCP service accounts remain logged in
+    for account in $(gcloud auth list --format 'value(account)' --filter=-account~$SA_SUFFIX)
+    do gcloud auth revoke $account
+    done
 }
 
 services() {
@@ -30,7 +39,7 @@ services() {
 }
 
 roles() {
-    member=serviceAccount:$email 
+    member=serviceAccount:$EMAIL
     for role in {compute,container,artifactregistry}.admin \
         resourcemanager.projectIamAdmin iam.serviceAccount{Admin,User}
     do gcloud projects $1-iam-policy-binding $PROJECT --member $member --role roles/$role
@@ -38,9 +47,12 @@ roles() {
 }
 
 setup() {
-    gcloud config configurations create $ALIAS
+    local config=$(gcloud config configurations list --format 'value(name)' --filter $ALIAS)
+    if [ "$config" = $ALIAS ]; then command=activate; else command=create; fi
+    gcloud config configurations $command $ALIAS
 
     gcloud config set project $PROJECT
+    gcloud config set account ""
 
     ensure_logged_in
     services enable
@@ -49,13 +61,15 @@ setup() {
     gcloud config set compute/region $REGION
     gcloud config set compute/zone $ZONE
 
-    gcloud iam service-accounts create $SA_NAME
+    [ "$(gcloud iam service-accounts list \
+        --format 'value(email)' \
+        --filter email=$EMAIL)" = $EMAIL ] || gcloud iam service-accounts create $SA_NAME
 
-    roles add
-
-    gcloud iam service-accounts keys create "$KEYFILE" --iam-account=$email
+    gcloud iam service-accounts keys create "$KEYFILE" --iam-account=$EMAIL
 
     gcloud auth activate-service-account --key-file "$KEYFILE" --project $PROJECT
+
+    roles add
 
     ensure_logged_out
 }
@@ -66,15 +80,15 @@ teardown() {
 
     ensure_logged_in
 
-    gcloud auth revoke $email
-
-    rm -vf "$KEYFILE"
-
     roles remove
     # DO NOT disable service API:s to avoid unexpected havoc
     # services disable
 
-    gcloud iam service-accounts delete $email --quiet
+    gcloud auth revoke $EMAIL
+
+    rm -vf "$KEYFILE"
+
+    gcloud iam service-accounts delete $EMAIL --quiet
 
     if [ "$(gcloud config configurations list --filter name=default --format 'value(name)')" ]
     then verb=activate
@@ -103,11 +117,12 @@ case $1 in
     =) 
         ;;
     "")
-        # return if the script is being sourced, otherwise fall through to usage
-        [[ "$0" == "${BASH_SOURCE[0]}" ]] || return 0
+        # turn off exit on error and return if the script is being sourced,
+        # otherwise fall through to usage
+        [[ "$0" == "${BASH_SOURCE[0]}" ]] || { set +e; return 0; }
         ;&
     *)
-        echo Usage: ${0##*/} [=\|+\|-]
+        echo Usage: $self [=\|+\|-]
         exit 1
 esac
 check || [ "$1" = - ]
